name: Ping Nadia

on:
  schedule:
    - cron: "0 12 * * 4"
  workflow_dispatch:

jobs:
  send-reminder-emails:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@releases/v1
        with:
          ENDPOINT: https://thursday-slack-bot.vercel.app/api
          CONFIGURATION: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.TOKEN }}"} }'
